### ISSUE TITLE
Wrong results when {host.name} includes a minus (-) character

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-elasticsearch#34] opened 2018-06-08 11:44 UTC
## Expected Behavior
If the host name contains a minus (-) character I only receive results for this host when querying elasticsearch like this:
`fields.host_name={host.name}`
hostname: `demo-host.local'

## Current Behavior
I receive results for all `fields.host_name` containing `demo` or `host.local`

## Possible Solution
Wrap the {host.name} in double quotes when translating to elasticsearch query

## Steps to Reproduce (for bugs)
Compare the results of the lucene queries
`fields.host_name:demo-host.local`
and
`fields.host_name:"demo-host.local"`

## Your Environment
* Module version (System - About): 1.0.0
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): 2.8.4
* Elasticsearch version (`curl http://localhost:9200`): 5.6
* Operating System and version: Debian 9.4
* Webserver, PHP versions: NGINX, PHP 7.0

**Comment by MarcusCaepio** [comment] 2018-07-31 09:40
I can confirm this. 
My filter:
![image](https://user-images.githubusercontent.com/7324088/43451876-4168628c-94b6-11e8-930e-640853daf961.png)
Result:
![image](https://user-images.githubusercontent.com/7324088/43451923-625ce364-94b6-11e8-9a2c-9b937aa02399.png)

**Comment by jediblair** [comment] 2018-10-04 23:30
see my response in the other duplicate issue here - https://github.com/Icinga/icingaweb2-module-elasticsearch/issues/26
You'll want to change your mapping type on your index to "keyword" for the hostname, or try using the .keyword type in your query.  - eg fields.host_name.keyword={host.name}

**Comment by lippserd** [comment] 2019-06-14 09:25
Duplicate of #26

**Closed by lippserd** 2019-06-14 09:25 UTC
